name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

env:
  APP_NAME: forms

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ["8.0", "8.1", "8.2"]
        # Upload coverage only once (out of php-versions)
        coverage-on: ['8.2']
        databases: ['sqlite']
        server-versions: ['master']
  
    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    steps:
      - name: Checkout server
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout circles dependency
        uses: actions/checkout@v3
        with:
          repository: nextcloud/circles
          ref: ${{ matrix.server-versions }}
          path: apps/circles

      - name: Checkout app
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, zip, gd
          coverage: xdebug

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
          OC_PASS: test
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          ./occ user:add --password-from-env --display-name="Test Displayname" test
          ./occ user:add --password-from-env --display-name="User No. 1" user1
          ./occ app:enable --force ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: PHPUnit & coverage
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:unit

      - name: PHPUnit integration
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:integration

      - name: Upload Unit coverage
        if: matrix.php-versions == matrix.coverage-on
        uses: codecov/codecov-action@v3
        with:
          root_dir: ./apps/${{ env.APP_NAME }}
          files: ./apps/${{ env.APP_NAME }}/tests/clover.unit.xml
          fail_ci_if_error: true
          flags: unit

      - name: Upload Integration coverage
        if: matrix.php-versions == matrix.coverage-on
        uses: codecov/codecov-action@v3
        with:
          root_dir: ./apps/${{ env.APP_NAME }}
          files: ./apps/${{ env.APP_NAME }}/tests/clover.integration.xml
          fail_ci_if_error: true
          flags: integration

  mysql:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        databases: ['mysql']
        server-versions: ['stable26', 'stable27', 'master']
  
    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    services:
      mysql:
        image: ghcr.io/nextcloud/continuous-integration-mariadb-10.11:latest
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout server
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout circles dependency
        uses: actions/checkout@v3
        with:
          repository: nextcloud/circles
          ref: ${{ matrix.server-versions }}
          path: apps/circles

      - name: Checkout app
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, mysql, pdo_mysql, zip, gd
          coverage: none

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
          OC_PASS: test
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          ./occ user:add --password-from-env --display-name="Test Displayname" test
          ./occ user:add --password-from-env --display-name="User No. 1" user1
          ./occ app:enable --force ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:unit

      - name: PHPUnit integration
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:integration

  pgsql:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        databases: ['pgsql']
        server-versions: ['master']
  
    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    services:
      postgres:
        image: ghcr.io/nextcloud/continuous-integration-postgres-15:latest
        ports:
          - 4444:5432/tcp
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: nextcloud
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout server
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout circles dependency
        uses: actions/checkout@v3
        with:
          repository: nextcloud/circles
          ref: ${{ matrix.server-versions }}
          path: apps/circles

      - name: Checkout app
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, pgsql, pdo_pgsql, zip, gd
          coverage: none

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
          OC_PASS: test
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          ./occ user:add --password-from-env --display-name="Test Displayname" test
          ./occ user:add --password-from-env --display-name="User No. 1" user1
          ./occ app:enable --force ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:unit

      - name: PHPUnit integration
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:integration

  oci:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        databases: ['oci']
        server-versions: ['master']

    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    services:
      oracle:
        image: ghcr.io/gvenzl/oracle-xe:11

        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: autotest
          APP_USER_PASSWORD: nextcloud

        # Forward Oracle port
        ports:
          - 1521:1521/tcp

        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout server
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout circles dependency
        uses: actions/checkout@v3
        with:
          repository: nextcloud/circles
          ref: ${{ matrix.server-versions }}
          path: apps/circles

      - name: Checkout app
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2
        with:
          php-version: ${{ matrix.php-versions }}
          # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, oci8
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 1521
          OC_PASS: test
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=autotest --database-pass=nextcloud --admin-user admin --admin-pass admin
          ./occ user:add --password-from-env --display-name="Test Displayname" test
          ./occ user:add --password-from-env --display-name="User No. 1" user1
          ./occ app:enable --force ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:unit

      - name: PHPUnit integration
        working-directory: apps/${{ env.APP_NAME }}
        run: composer test:integration
